"""initial migration

Revision ID: 75d405df4666
Revises: 6e309f1e9739
Create Date: 2018-08-09 11:09:20.614448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d405df4666'
down_revision = '6e309f1e9739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'height')
    # ### end Alembic commands ###
